app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.dashboard, name="user_dashboard"),
    path("dashboard/", views.dashboard, name="user_dashboard"),
    path("surgical-areas/", views.surgical_areas, name="user_surgical_areas"),
    path("surgery-types/", views.surgery_types, name="user_surgery_types"),
    path("surgery-types/<int:surgical_area_id>/", views.surgery_types, name="user_surgery_types"),
    path("peripheral-blocks/", views.peripheral_blocks, name="user_peripheral_blocks"),
    path("peripheral-blocks/<int:surgery_type_id>/", views.peripheral_blocks, name="user_peripheral_blocks"),
    path("peripheral-block/<int:peripheral_block_id>/", views.peripheral_block, name="user_peripheral_block"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Default path to index
    path("", views.index, name="app_index"),

    # Delegate paths to each subapplication
    path("administration/", include("administration.urls")),
    path("app/", include("app.urls")),
    path("users/", include("users.urls")),
    path("logs/", include("logs.urls")),

    # Django admin path
    path('admin/', admin.site.urls),
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = 'core.views.custom_403'
handler404 = 'core.views.custom_404'
handler500 = 'core.views.custom_500'

users/urls.py
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.urls import include, path
from . import views
from .views import ResetPasswordView

urlpatterns = [
    # Path to non logged users
    path("", lambda request: redirect("access/"), name="principal_redirection"), # Redirect from main url ("/") to ("/access/")
    path("access/", views.access, name="access"),
    path("register/", views.register, name="register"),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('passwordreset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/unlogged/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/unlogged/password_reset_complete.html'), name='password_reset_complete'),
    path('auth-receiver', views.auth_receiver, name='auth_receiver'), # Endpoint to Google Auth

    # Paths to logged users
    path("exit/", views.exit, name="exit"),
    path("profile/", views.profile, name="profile"),
    path("subscription/", views.subscription, name="user_subscription"),

    # Paths of Payments use
    path("stripe_webhook/", views.stripe_webhook, name="stripe_webhook"),
    path("cancel_subscription/<str:payment_subscription_id>/", views.cancel_subscription, name="cancel_subscription"),
    path("paypal/", views.paypal, name="paypal"),
    path("successful/", views.successful, name="paypal_successful"),
    path("cancelled/", views.cancelled, name="paypal_cancelled"),
    path("stripe_checkout/<str:product_id>/", views.stripe_checkout, name="stripe_checkout"),
]

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.utils import timezone
from uuid import uuid4
import uuid



def custom_upload_to(instance, filename):
    """
    Generate a filename based on a UUID.
    """
    ext = filename.split('.')[-1] # Get file extension
    filename = f"{uuid4().hex}.{ext}" # Generate unique file name using UUID
    return f"profile_pics/{filename}" # Return file path with name



    

class CustomUser(AbstractUser):
    
    pic = models.ImageField(upload_to=custom_upload_to, null=True, blank=True)
    groups = models.ManyToManyField(Group, related_name='custom_user_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_user_permissions')


    def is_premium(self):
        return user_is_premium(self.pk)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import CustomUser
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django_recaptcha.fields import ReCaptchaField

class CustomAuthenticationForm(AuthenticationForm):
    captcha = ReCaptchaField()

    class Meta:
        model = CustomUser
        fields = ('username', 'password', 'captcha')

class CustomUserCreationForm(UserCreationForm):
    captcha = ReCaptchaField()
    first_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'password1', 'captcha')

class CustomUserCreationByAdminForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'pic')


class CustomUserEditByAdminForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'pic']


class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'pic']


class CustomPasswordChangeForm(forms.Form):
    
    user = None
    new_password1 = forms.CharField(
        label=("New password"),
        strip=False,
        widget=forms.PasswordInput,
    )
    new_password2 = forms.CharField(
        label=("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2:
            if new_password1 != new_password2:
                raise forms.ValidationError(
                    'The two password fields didn’t match.'
                )
        return cleaned_data

    def save(self):
        user = self.user
        user.set_password(self.cleaned_data['new_password1'])
        user.save()

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.decorators import login_required 
from django.views.decorators.csrf import csrf_exempt
from google.oauth2 import id_token
from google.auth.transport import requests as google_auth_requests
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CustomUserCreationForm, CustomUserEditForm, CustomAuthenticationForm
from .models import CustomUser
from appmodels.models import GeneralConfig, Product, Subscription
from paypal.standard.forms import PayPalPaymentsForm
from utils.functions import get_client_geolocation
from django.conf import settings
import requests
from django.contrib import messages
import jwt
import os
from mimetypes import guess_extension
import uuid
from logs.views import log
from django.core.files.base import ContentFile
from django.core.files.temp import NamedTemporaryFile
from datetime import timedelta
from utils.functions import write_in_log_file
import json
from django.db.models import Q
import stripe
import random

from utils.payment_gateway_paypal import (
    paypal_handle_event,
    paypal_handle_subscription_created,
    paypal_handle_subscription_activated,
    paypal_handle_payment_completed,
    paypal_handle_subscription_cancelled,
    paypal_handle_subscription_updated,
    paypal_handle_subscription_payment_failed
)

from utils.payment_gateway_stripe import (
    stripe_handle_event,
    stripe_handle_subscription_updated,
    stripe_handle_invoice_paid,
    stripe_handle_checkout_session_completed,
    stripe_handle_payment_failed,
    stripe_handle_subscription_deleted
)



PAYPAL_API_URL = "https://api-m.sandbox.paypal.com/"


def access(request):
    context = {}
    context['config'] = get_object_or_404(GeneralConfig, id=1)

    # Check if user is already logged
    if request.user.is_authenticated:
        if request.user.groups.filter(name='Administration').exists():
            log(request, "UserLog", {"action_type":"read", "status":302, "details":"Admin already logged", "change_by_admin":False})
            return redirect('/administration/dashboard')
        else:
            log(request, "UserLog", {"action_type":"read", "status":302, "details":"Non privileged user already logged", "change_by_admin":False})
            return redirect('/app/dashboard')

    if request.method == "POST":
        # Trying signin
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username_form = form.cleaned_data.get('username')
            password_form = form.cleaned_data.get('password')
            user = authenticate(username=username_form, password=password_form)

            if user is not None:
                login(request, user)
                if user.groups.filter(name='Administration').exists():
                    log(request, "UserLog", {"action_type":"read", "status":200, "details":"Granted access as admin through credentials", "change_by_admin":False})
                    return redirect('/administration/dashboard')
                else:
                    log(request, "UserLog", {"action_type":"read", "status":200, "details":"Granted access as non privileged user through credentials", "change_by_admin":False})
                    return redirect('/app/dashboard')

            log(request, "UserLog", {"action_type":"read", "status":400, "details":"Error trying login", "change_by_admin":False})
        else:
            log(request, "UserLog", {"action_type":"read", "status":403, "details":"Invalid login form", "change_by_admin":False})
            
        context['errors'] = form.errors

        context["signin_message"] = "All fields are required."


    # No POST, new form
    form = CustomAuthenticationForm()
    form.fields['username'].widget.attrs.update({'class': 'form-control','placeholder':'Email','type':'email'})
    form.fields['password'].widget.attrs.update({'class': 'form-control','placeholder':'Password','type':'password'})
    context["form"] = form

    log(request, "UserLog", {"action_type":"read", "status":200, "details":"Load access page", "change_by_admin":False})

    return render(request, "users/unlogged/access.html", context=context)


def register(request):
    context = {}
    context['config'] = get_object_or_404(GeneralConfig, id=1)

    # Check if user is already logged
    if request.user.is_authenticated:
        if request.user.groups.filter(name='Administration').exists():
            log(request, "UserLog", {"action_type":"create", "status":302, "details":"Admin already logged", "change_by_admin":False})
            return redirect('/administration/dashboard')
        else:
            log(request, "UserLog", {"action_type":"create", "status":302, "details":"Non privileged user already logged", "change_by_admin":False})
            return redirect('/app/dashboard')

    if request.method == "POST":
        # Trying signup
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()  # Save registered user
            log(request, "UserLog", {"action_type":"create", "status":200, "details":"Create user through credentials", "change_by_admin":False, "new_user":new_user})
            return redirect('/')
        else:
            log(request, "UserLog", {"action_type":"create", "status":400, "details":"Create user", "change_by_admin":False})
            context["signup_message"] = "All fields are required."
            context["errors"] = form.errors
    
        context['errors'] = form.errors

    form = CustomUserCreationForm()
    form.fields['username'].widget.attrs.update({'class': 'form-control','placeholder':'Email','type':'email'})
    form.fields['password1'].widget.attrs.update({'class': 'form-control','placeholder':'Password','type':'password'})
    form.fields['password2'].widget.attrs.update({'class': 'form-control','placeholder':'Retype password','type':'password'})
    form.fields['first_name'].widget.attrs.update({'class': 'form-control','placeholder':'Name','type':'text'})
    context['form'] = form

    log(request, "UserLog", {"action_type":"read", "status":200, "details":"Load register", "change_by_admin":False})
    return render(request, "users/unlogged/register.html", context=context)
    

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/unlogged/password_reset.html'
    email_template_name = 'users/unlogged/password_reset_email.html'
    subject_template_name = 'users/unlogged/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('access')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['config'] = get_object_or_404(GeneralConfig, id=1)
        return context


def exit(request):
    logout(request)
    return redirect('/')


@login_required(login_url="/users/access")
def profile(request):
    custom_user = get_object_or_404(CustomUser, id=request.user.id)
    context = {}
    if request.method == 'POST':
        form = CustomUserEditForm(request.POST, request.FILES, instance=custom_user)
        if form.is_valid():
            custom_user.save()
            log(request, "UserLog", {"action_type":"update", "status":200, "details":"Updated profile", "change_by_admin":False})
            messages.success(request, f"User profile successfully updated")
            return redirect('/users/profile')
        else:
            log(request, "UserLog", {"action_type":"update", "status":400, "details":"Error updating profile", "change_by_admin":False})
            context['errors'] = form.errors

    form = CustomUserEditForm(instance=custom_user)
    form.fields['pic'].widget.attrs.update({'class': 'form-control'})
    form.fields['username'].widget.attrs.update({'class': 'form-control','placeholder':'Email','type':'email'})
    form.fields['first_name'].widget.attrs.update({'class': 'form-control','placeholder':'Name','type':'text'})
    form.fields['last_name'].widget.attrs.update({'class': 'form-control','placeholder':'Name','type':'text'})
    
    context['form'] = form
    context['config'] = get_object_or_404(GeneralConfig, id=1)
    log(request, "UserLog", {"action_type":"read", "status":200, "details":"Load profile", "change_by_admin":False})
    return render (request, "users/logged/profile.html", context)


@login_required(login_url="/users/access")
def subscription(request):
    context = {}
    context['config'] = get_object_or_404(GeneralConfig, id=1)
    context['products'] = Product.objects.filter(public=True).order_by('price')
    context['subscriptions'] = Subscription.objects.filter(user=request.user).exclude(status='HIDDEN').order_by('-payment_datetime')
    context['today'] = timezone.now() 

    # Check if current user has an active subscription
    today = timezone.now().date()
    active_subscription = Subscription.objects.filter(user=request.user, due_date__gt=today).first()
    if active_subscription:        
        context['active_subscription'] = active_subscription
    else:
        context['active_subscription'] = None

    return render(request, "users/logged/subscription.html", context)


@csrf_exempt
def auth_receiver(request):
    """
    Google calls this URL after the user has signed in with their Google account.
    """

templates/users/unlogged/access.html
{% extends 'users/unlogged/base.html' %}

{% block content %}

<div class="login_wrapper">
  <div class="animate form login_form">
    <section class="login_content">
      <form method="post" action="{% url 'access' %}">
        {% csrf_token %}
        <h1>Access</h1>
        <div>
          {{ form.username }}
        </div>
        <div>
          {{ form.password }}
        </div>
        <div style='text-align: -webkit-center;'>
          {{ form.captcha }}
        </div>
        <div class="text-danger" style='margin-top:20px;'>{{signin_message}}</div>
        <div style='margin-top:20px;'>
          <button type="submit" class="btn btn-default submit">Log in</button>
        </div>

        <div class="clearfix"></div>

        <div class="separator">
          <p class="change_link">New to site?
            <a href="{% url 'register' %}" class="to_register"> Create Account </a>
          </p>
          <p class="change_link">
            <a href="{% url 'password_reset' %}" class="to_register"> Lost your password?</a>
          </p>

          <div class="clearfix"></div>
          <br />

          {% if config.google_oauth_client_id %}
          <div id="g_id_onload"
                data-client_id="{{ config.google_oauth_client_id }}"
                data-context="signup"
                data-ux_mode="redirect"
                data-login_uri="{{ config.app_url }}users/auth-receiver"
                data-itp_support="true">
            </div>

            <div class="g_id_signin"
                data-type="standard"
                data-shape="rectangular"
                data-theme="outline"
                data-text="Access with Google"
                data-size="large"
                data-logo_alignment="left">
            </div>
            {% endif %}


          <div class="clearfix"></div>
          <br />

          <div>
            <h1><i class="{{config.app_icon}}"></i> {{config.app_name}}</h1>
            <p>©
              <script>document.write(new Date().getFullYear());</script> All Rights Reserved.
              {{config.app_name}}.<br />Privacy and Terms
            </p>
          </div>
        </div>
      </form>
    </section>
  </div>
</div>
{% endblock content %}

templates/users/unlogged/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/ico" />

    <title>{% block title %} {{config.app_name}} {% endblock %}</title>

    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>

    <!-- Google OAuth -->
    <script src="https://accounts.google.com/gsi/client" async></script>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <!-- NProgress -->
    <link href="{% static 'app/vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'app/vendors/animate.css/animate.min.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'app/build/css/custom.min.css' %}" rel="stylesheet">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
        integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>

    <style>
        .btn,
        .btn:hover {
        border: 1px #5A738E solid;
        }
    </style>
    <!-- Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ config.google_analytics_tag_id }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{ config.google_analytics_tag_id }}');
    </script>
    </head>

    <body class="login">

            {% block content %}

            {% endblock %} 

        </div>
</html>

templates/users/unlogged/password_reset.html
{% extends 'users/unlogged/base.html' %}

{% block content %}

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form method="post" action="{% url 'password_reset' %}">
              {% csrf_token %}
              <h1>Recovery password</h1>
              <div>
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                                <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                
                <input type="text" name="email" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="form-control" placeholder="Email" required="" id="id_email">

              </div>
              <div class="text-danger">{{signin_message}}</div>
              <div>
                <button type="submit" class="btn btn-default submit">Send me instructions!</button>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">New to site?
                  <a href="{% url 'register' %}" class="to_register"> Create Account </a>
                </p>
                <p class="change_link">Already a member ?
                  <a href="{% url 'access' %}" class="to_register"> Log in </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="{{config.app_icon}}"></i> {{config.app_name}}</h1>
                  <p>©<script>document.write(new Date().getFullYear());</script> All Rights Reserved. {{config.app_name}}.<br/>Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>

{% endblock content %}

templates/users/unlogged/password_reset_complete.html
{% extends 'users/unlogged/base.html' %}
{% block title %} Easy Regional Block {% endblock %}
{% block content %}
    <meta http-equiv="refresh" content="3; URL='{% url 'access' %}'" />    
        <div class="login_wrapper">
        <div class="animate form login_form">
            <div class="alert alert-info" style="text-align: -webkit-center;">
                Your password has been changed.<br/>If you are not redirected in five seconds, <a href="{% url 'access' %}">click here</a>
            </div>
        </div>
    </div>

{% endblock content %}

templates/users/unlogged/password_reset_confirm.html
{% extends 'users/unlogged/base.html' %}
{% block title %} Easy Regional Block {% endblock %}
{% block content %}

      <div class="login_wrapper">
        <div class="animate form login_form">
        {% if validlink %}
          <section class="login_content">
            <form method="post">
              {% csrf_token %}
              <h1>Reset Your Password</h1>
              <div>
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <div id="form_errors">
                            {% for key, value in form.errors.items %}
                                <strong>{{ value }}</strong>
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                
                <input id="id_new_password1" type="password" name="new_password1" autocomplete="new-password" class="form-control" maxlength="150" placeholder="Enter password" required/>
                
                <input id="id_new_password2" type="password" name="new_password2" autocomplete="new-password" class="form-control" maxlength="150" placeholder="Confirm password" required/>

              </div>
              <div>
                <button type="submit" class="btn btn-default submit">Reset password now!</button>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
               
                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="{{config.app_icon}}"></i> {{config.app_name}}</h1>
                  <p>©<script>document.write(new Date().getFullYear());</script> All Rights Reserved. {{config.app_name}}.<br/>Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        {% else %}
            <div class="alert alert-warning" style="text-align: -webkit-center;">
                The password reset link was invalid, possibly because it has already been used.
                Please request a new password reset.
            </div>
        {% endif %}
        </div>
      </div>

{% endblock content %}

templates/users/unlogged/password_reset_email.html
{% autoescape off %}
  Dear {{ user.email }},

  To initiate the password reset process for your user in Easy Regional Block,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  ERB Team | Easy Regional Block

{% endautoescape %}

templates/users/unlogged/register.html
{% extends 'users/unlogged/base.html' %}

{% block content %}

      <div class="login_wrapper">
        <div id="register" class="animate form login_form">
          <section class="login_content">
            <form method="post" action="{% url 'register' %}">
              {% csrf_token %}
              <h1>Create an account</h1>
              <div>
                {{ form.username }}
              </div>
              <div>
                {{ form.password1 }}
              </div>
              <div>
                {{ form.password2 }}
              </div>
              <div>
                {{ form.first_name }}
              </div>
              <div style='text-align: -webkit-center;'>
                {{ form.captcha }}
              </div>
              
              <div class="text-danger">
                {% if errors %}
                  <ul>
                      {% for field, errors_list in errors.items %}
                          {% for error in errors_list %}
                              <li style='text-align-last: left;'>{{ error }}</li>
                          {% endfor %}
                      {% endfor %}
                  </ul>
                {% endif %}
              </div>


              <div style='margin-top:20px;'>
                <button type="submit" class="btn btn-default submit">Register</button>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">Already a member ?
                  <a href="{% url 'access' %}" class="to_register"> Log in </a>
                </p>
                <p class="change_link">
                  <a href="{% url 'password_reset' %}" class="to_register"> Lost your password?</a>
                </p>

                <div class="clearfix"></div>
                <br />

                {% if config.google_oauth_client_id %}
                <div id="g_id_onload"
                      data-client_id="{{ config.google_oauth_client_id }}"
                      data-context="signup"
                      data-ux_mode="redirect"
                      data-login_uri="{{ config.app_url }}users/auth-receiver"
                      data-itp_support="true">
                  </div>
      
                  <div class="g_id_signin"
                      data-type="standard"
                      data-shape="rectangular"
                      data-theme="outline"
                      data-text="Access with Google"
                      data-size="large"
                      data-logo_alignment="left">
                  </div>
                  {% endif %}
      
      
                <div class="clearfix"></div>
                <br />
      
                <div>
                  <h1><i class="{{config.app_icon}}"></i> {{config.app_name}}</h1>
                  <p>©<script>document.write(new Date().getFullYear());</script> All Rights Reserved. {{config.app_name}}.<br/>Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
      {% endblock content %}