administration/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path("dashboard/", views.dashboard, name="administration_dashboard"),
    path("parameters/", views.parameters, name="administration_parameters"),
    
    path("products/", views.products, name="administration_products"),
    path("product_add/", views.product_add, name="administration_product_add"),
    path("product_edit/<int:product_id>/", views.product_edit, name="administration_product_edit"),
    path("product_delete/<int:product_id>/", views.product_delete, name="administration_product_delete"),
    
    path("posts/", views.blogs, name="administration_blogs"),
    path("post-add/", views.blog_add, name="administration_blog_add"),
    path("post-edit/<int:blog_id>/", views.blog_edit, name="administration_blog_edit"),
    path("post-delete/<int:blog_id>/", views.blog_delete, name="administration_blog_delete"),
    
    path("subscriptions/", views.subscriptions, name="administration_subscriptions"),
    path("subscription_add/", views.subscription_add, name="administration_subscription_add"),
    path("subscription_edit/<int:subscription_id>/", views.subscription_edit, name="administration_subscription_edit"),
    path("subscription_delete/<int:subscription_id>/", views.subscription_delete, name="administration_subscription_delete"),
    path("assign_product/", views.assign_product, name="administration_assign_product"),

    path("users/", views.users, name="administration_users"),
    path("user_add/", views.user_add, name="administration_user_add"),
    path("user_edit/<int:custom_user_id>/", views.user_edit, name="administration_user_edit"),
    path("user_delete/<int:custom_user_id>/", views.user_delete, name="administration_user_delete"),
    path("user_make_admin/<int:custom_user_id>/", views.user_make_admin, name="administration_user_make_admin"),
    path("user_deactivate_account/<int:custom_user_id>/", views.user_deactivate_account, name="administration_user_deactivate_account"),
    
    path("surgical_areas/", views.surgical_areas, name="administration_surgical_areas"),
    path("surgical_area_add/", views.surgical_area_add, name="administration_surgical_area_add"),
    path("surgical_area_edit/<int:surgical_area_id>/", views.surgical_area_edit, name="administration_surgical_area_edit"),
    path("surgical_area_delete/<int:surgical_area_id>/", views.surgical_area_delete, name="administration_surgical_area_delete"),
    
    path("surgery_types/", views.surgery_types, name="administration_surgery_types"),
    path("surgery_type_add/", views.surgery_type_add, name="administration_surgery_type_add"),
    path("surgery_type_edit/<int:surgery_type_id>/", views.surgery_type_edit, name="administration_surgery_type_edit"),
    path("surgery_type_delete/<int:surgery_type_id>/", views.surgery_type_delete, name="administration_surgery_type_delete"),
    path("get_surgery_types_by_surgical_area/<int:surgical_area_id>/", views.get_surgery_types_by_surgical_area, name="administration_get_surgery_types_by_surgical_area"),

    path("peripheral_blocks/", views.peripheral_blocks, name="administration_peripheral_blocks"),
    path("peripheral_block_add/", views.peripheral_block_add, name="administration_peripheral_block_add"),
    path("peripheral_block_edit/<int:peripheral_block_id>/", views.peripheral_block_edit, name="administration_peripheral_block_edit"),
    path("peripheral_block_delete/<int:peripheral_block_id>/", views.peripheral_block_delete, name="administration_peripheral_block_delete"),
    path("peripheral_block_gallery/<int:peripheral_block_id>/", views.peripheral_block_gallery, name="administration_peripheral_block_gallery"),
    path("peripheral_block_image_delete/<int:image_id>/", views.peripheral_block_image_delete, name="administration_peripheral_block_image_delete"),

    path("logs/", views.logs, name="administration_logs"),
    path('get_log_details/<str:log_type>/<int:log_id>', views.get_log_details, name='administration_get_log_details'),


]

app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.dashboard, name="user_dashboard"),
    path("dashboard/", views.dashboard, name="user_dashboard"),
    path("surgical-areas/", views.surgical_areas, name="user_surgical_areas"),
    path("surgery-types/", views.surgery_types, name="user_surgery_types"),
    path("surgery-types/<int:surgical_area_id>/", views.surgery_types, name="user_surgery_types"),
    path("peripheral-blocks/", views.peripheral_blocks, name="user_peripheral_blocks"),
    path("peripheral-blocks/<int:surgery_type_id>/", views.peripheral_blocks, name="user_peripheral_blocks"),
    path("peripheral-block/<int:peripheral_block_id>/", views.peripheral_block, name="user_peripheral_block"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Default path to index
    path("", views.index, name="app_index"),

    # Delegate paths to each subapplication
    path("administration/", include("administration.urls")),
    path("app/", include("app.urls")),
    path("users/", include("users.urls")),
    path("logs/", include("logs.urls")),

    # Django admin path
    path('admin/', admin.site.urls),
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler403 = 'core.views.custom_403'
handler404 = 'core.views.custom_404'
handler500 = 'core.views.custom_500'

administration/models.py
from django.db import models

# Create your models here.

logs/models.py
from django.db import models
from users.models import CustomUser
from appmodels.models import Subscription, SurgicalArea, SurgeryType, PeripheralBlock, Product

class GeneralLog(models.Model):
    """
    Abstract class to define the general schema of each log 
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="%(class)s_logs", null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    action_type = models.CharField(max_length=100, null=False, blank=False, default='')
    status = models.CharField(max_length=100, null=False, blank=False, default='')
    details = models.TextField(blank=True) # Extra information
    ip = models.CharField(max_length=20, null=False, blank=False, default='')
    continent = models.CharField(max_length=100, null=False, blank=False, default='')
    country = models.CharField(max_length=100, null=False, blank=False, default='')
    region = models.CharField(max_length=200, null=False, blank=False, default='')
    city = models.CharField(max_length=200, null=False, blank=False, default='')
    postal = models.CharField(max_length=20, null=False, blank=False, default='')
    lat = models.CharField(max_length=20, null=False, blank=False, default='') 
    lng = models.CharField(max_length=20, null=False, blank=False, default='') 

    class Meta:
        abstract = True


class UserLog(GeneralLog):
    """
    Class to register user events
    Action options: register, login, logout, recovery password, etc
    """
    change_by_admin = models.BooleanField(default=False)

class AdminsLog(GeneralLog):
    """
    Class to register admin events
    Action options: create, read, list, update, delete
    """
    item = models.CharField(max_length=100) # Options: SurgicalArea, SurgeryType, PeripheralBlock, Parameters, Subscription, Product
    
class SubscriptionLog(GeneralLog):
    """
    Class to register subscription events
    Action options: create, read, update, delete
    """
    payment_gateway = models.CharField(max_length=100, null=True, blank=True, default='') # i.e. Paypal, Stripe, Other which comes from subscription object choices
    receptor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True, default=None) # User who receives the subscription
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, default=None) # Product object reference
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE, null=True, blank=True, default=None) # subscription object reference
    payment_gateway_details = models.TextField(blank=True, null= True) # Payment gateway important information about subscription (cus_ in_ ...)
    payload = models.TextField(blank=True, null= True) # Payload from Payment gateway event
    
class TrackingLog(GeneralLog):
    """
    Class to register users tracking events
    Action options: create, read, update, delete
    """
    has_active_subscription = models.BooleanField(default=False)
    surgical_area = models.ForeignKey(SurgicalArea, on_delete=models.CASCADE, null=True, blank=True, default=None)
    surgery_type = models.ForeignKey(SurgeryType, on_delete=models.CASCADE, null=True, blank=True, default=None)
    peripheral_block = models.ForeignKey(PeripheralBlock, on_delete=models.CASCADE, null=True, blank=True, default=None)

templates/administration/peripheral_block/peripheral_block_add.html
{% extends '../../base/base.html' %}
{% block content %}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Peripheral blocks</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row" style="display: block;">

            <div class="clearfix"></div>

            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Add new peripheral block</h2>

                        {% if messages %}
                        <script>
                            function hide_message() {
                                const message_label = document.querySelector("#message");
                                message_label.style.display = "none";
                            }
                        </script>
                        {% for message in messages %}
                        <p id="message" {% if message.tags %} class="messages {{ message.tags }}" {% endif %}
                            style="text-align: -webkit-center;color:{{config.app_color_1}};font-weight:800;margin-top:30px; margin-bottom:9px;">
                            {{ message }} <i class="fa-solid fa-circle-xmark" onclick="hide_message()"></i></p>
                        {% endfor %}
                        {% endif %}

                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">





                        <form action="" role="form" method="POST" class="text-start" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="tab-content" id="myTabContent">

                                <div class="tab-pane fade show active" id="general" role="tabpanel"
                                    aria-labelledby="general-tab">
                                    <div class="seccion bg-gray-100 border-radius-lg">

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Surgical area</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.surgical_area }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Surgery type</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.surgery_type }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Title</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.title }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Description</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.description }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Video link</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <small class="form-text text-muted">Uploaded in <a
                                                        href="https://vimeo.com/">Vimeo</a></small>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.video_link }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Public access</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <small class="form-text text-muted">Take values 0 or 1</small>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <div
                                                    class="input-group input-group-outline mb-3">
                                                    <p class="p-class">{{ form.public }}</p>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            {{message}}
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary"
                                    style="background:{{ config.app_color_2 }};border:1px solid {{ config.app_color_1 }}">Save
                                    <i class="fa-solid fa-check" style="font-size:0.875rem"></i></button>
                            </div>
                        </form>




                        <script>
                            $(document).ready(function() {
                                $('#id_surgical_area').change(function() {
                                    var id_surgical_area = $(this).val();  // Get surgical area id
                                    if (id_surgical_area) {
                                        $.ajax({
                                            url: '/administration/get_surgery_types_by_surgical_area/' + id_surgical_area + '/',
                                            type: 'GET',
                                            dataType: 'json',
                                            success: function(data) {
                                                // Drop every presetted option
                                                $('#id_surgery_type').empty();
                      
                                                // Add each surgery type gotten from de API
                                                $.each(data, function(index, surgery_type) {
                                                    $('#id_surgery_type').append($('<option>', {
                                                        value: surgery_type.id,
                                                        text: surgery_type.title
                                                    }));
                                                });
                                            }
                                        });
                                    } else {
                                        // If there are no surgical area selected, clear the second select
                                        $('#id_surgery_type').empty();
                                    }
                                });
                            });
                            </script>



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

{% endblock %}

templates/administration/peripheral_block/peripheral_block_edit.html
{% extends '../../base/base.html' %}
{% block content %}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Peripheral blocks</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row" style="display: block;">

            <div class="clearfix"></div>

            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Edit peripheral block</h2>

                        {% if messages %}
                            <script>
                                function hide_message() {
                                    const message_label = document.querySelector("#message");
                                    message_label.style.display = "none";
                                }
                            </script>
                            {% for message in messages %}
                            <p id="message" {% if message.tags %} class="messages {{ message.tags }}" {% endif %}
                                style="text-align: -webkit-center;color:{{config.app_color_1}};font-weight:800;margin-top:30px; margin-bottom:9px;">
                                {{ message }} <i class="fa-solid fa-circle-xmark" onclick="hide_message()"></i></p>
                            {% endfor %}
                        {% endif %}

                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">





                        <form action="" role="form" method="POST" class="text-start" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="tab-content" id="myTabContent">

                                <div class="tab-pane fade show active" id="general" role="tabpanel"
                                    aria-labelledby="general-tab">
                                    <div class="seccion bg-gray-100 border-radius-lg">

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Surgical area</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.surgical_area }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Surgery type</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.surgery_type }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Title</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.title }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Description</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.description }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Video link</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <small class="form-text text-muted">Uploaded in <a
                                                        href="https://vimeo.com/">Vimeo</a></small>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <p class="p-class">{{ form.video_link }}</p>
                                            </div>
                                        </div>

                                        <div class="campo-agrupado input-group input-group-outline">
                                            <div class="col-md-12 col-sm-12 title-in-tag">
                                                <div class="font-weight-bold">Public access</div>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <small class="form-text text-muted">Take values 0 or 1</small>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <div
                                                    class="input-group input-group-outline mb-3">
                                                    <p class="p-class">{{ form.public }}</p>
                                                </div>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                            </div>

                            {{message}}
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary"
                                    style="background:{{ config.app_color_2 }};border:1px solid {{ config.app_color_1 }}">Save
                                    <i class="fa-solid fa-check" style="font-size:0.875rem"></i></button>
                            </div>
                        </form>




                        <script>
                            $(document).ready(function() {
                                $('#id_surgical_area').change(function() {
                                    var id_surgical_area = $(this).val();  // Get surgical area id
                                    if (id_surgical_area) {
                                        $.ajax({
                                            url: '/administration/get_surgery_types_by_surgical_area/' + id_surgical_area + '/',
                                            type: 'GET',
                                            dataType: 'json',
                                            success: function(data) {
                                                // Drop every presetted option
                                                $('#id_surgery_type').empty();
                      
                                                // Add each surgery type gotten from de API
                                                $.each(data, function(index, surgery_type) {
                                                    $('#id_surgery_type').append($('<option>', {
                                                        value: surgery_type.id,
                                                        text: surgery_type.title
                                                    }));
                                                });
                                            }
                                        });
                                    } else {
                                        // If there are no surgical area selected, clear the second select
                                        $('#id_surgery_type').empty();
                                    }
                                });
                            });
                            </script>



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

{% endblock %}